### ISSUE TITLE
Enable downstream libraries to publish to crates.io

### ISSUE THREAD

**Issue by sanderpick** [consensus-shipyard/ipc#1000]
We have an [SDK](https://github.com/textileio/basin/tree/main/sdk) that depends on IPC. We'd like to publish this to crates.io at some point.

To enable libraries that depend on IPC to publish to crates.io, all IPC dependencies need to have a version specified. Outstanding git dependencies:

- [x] The `merkle-tree-rs` patch, done in #940.
- [ ] `libp2p-bitswap = { git = "https://github.com/consensus-shipyard/libp2p-bitswap.git", branch = "chore-upgrade-libipld" }`: Looks to be covered by issue #970.
- [ ] `builtin-actors`: I don't see why this couldn't be published. I could open an issue on that repo. We have a custom fork of this, which we'd have to publish as well under some other domain.
- [ ] `gcra = { git = "https://github.com/consensus-shipyard/gcra-rs.git", branch = "main" }`: Could this be absored like what was done in #940 for `merkle-tree-rs`?

**Comment by raulk** [comment]
@cryptoAtwill could you own absorbing gcra-rs? Should be a quick win!

**Comment by sanderpick** [comment]
> ## consensus-shipyard/builtin-actors
> I don't think this dependency is actually needed; it might be a leftover from a previous version of the world where IPC actors were being developed as Wasm actors. Let's clean this up.

But IPC does use a handful of the builtin-actors. All [these fendermint actors](https://github.com/consensus-shipyard/ipc/tree/main/fendermint/actors) use `fil_actors_runtime`, and the [fendermint `eam`](https://github.com/consensus-shipyard/ipc/tree/main/fendermint/actors/eam) uses `fil_actors_evm_shared` and `fil_actor_eam`.

**Comment by stbrody** [comment]
@raulk any update on this?  This is going to become blocking for our release pretty soon as we can't easily publish our own crates for our SDK without this.

**Comment by cryptoAtwill** [comment]
@sanderpick @stbrody @raulk replacing the bitswap with forest implementation will take quite some time. The bitswap crate is used in ipld-resolver, but it's not actively used by the fendermint code base at the moment. For a quicker solution, would do something like `ext/bitswap` work for you?
