### ISSUE TITLE
IPC: Top-down cross-net primitives

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#197]
This issue collects all the tasks pending for the implementation of top-down cross-net primitives. Validators in child subnets periodically agree on the finality seen on their parent. This information is used to automatically propagate changes in membership for the subnet, and to trigger the execution of top-down cross-net messages. With this, peers in the network can join and leave subnets in a permissionless manner, fund their accounts in subnets, and send top-down cross-net messages.

```[tasklist]
### Tasks
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/200
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/201 
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/213
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/214
- [ ] https://github.com/consensus-shipyard/fendermint/issues/242
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/274
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/158
```
