### ISSUE TITLE
IPC: Lifecycle of a subnet

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#199]
This issue collects all the pending tasks to wrap-up the implementation of the lifecycle of subnets over Fendermint.
```[tasklist]
### Tasks
- [ ] https://github.com/consensus-shipyard/fendermint/issues/301
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/232
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/233
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/330
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/323
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/349
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/351
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/273
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/333
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/196
```
