### ISSUE TITLE
IPC: Checkpoint construction in the child subnet

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/ipc#211]
This is the other half of consensus-shipyard/ipc-monorepo#231 dealing with the construction and relaying of a checkpoint from the child subnet to the parent. 

Unlike consensus-shipyard/ipc-monorepo#231 which is only relevant if Fendermint itself has child subnets, this one is needed for Fendermint acting as a subnet of the Lotus rootnet. 

```[tasklist]
### Tasks
- [ ] https://github.com/consensus-shipyard/fendermint/issues/244
- [ ] https://github.com/consensus-shipyard/fendermint/issues/245
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/208
- [ ] https://github.com/consensus-shipyard/fendermint/issues/247
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/206
- [ ] https://github.com/consensus-shipyard/fendermint/issues/249
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/204
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/306
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/305
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/304
- [ ] https://github.com/consensus-shipyard/fendermint/issues/254
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/302
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/301
- [ ] https://github.com/consensus-shipyard/fendermint/issues/257
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/299
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/298
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/203
- [ ] https://github.com/consensus-shipyard/fendermint/issues/261
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/284
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/283
- [ ] https://github.com/consensus-shipyard/fendermint/issues/283
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/281
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/279
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/278
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/277
- [ ] https://github.com/consensus-shipyard/fendermint/issues/303
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/275
```
