### ISSUE TITLE
Use Ethereum address in events and filters

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/ipc#226]
```[tasklist]
### Tasks
- [x] Event emitter turned into Ethereum address, not masked ID
- [x] Filter subscriptions turn Ethereum address back into ID for the filter expression
- [x] Return Ethereum address from contract creation
```
