### ISSUE TITLE
IPC: Checkpoint handling in the parent subnet

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#231]
The design has been [moved to the following doc](https://docs.google.com/document/d/19o-gK7C5QMFZmNE9npI2mr9MIJpEDvznRzK30g89wZk/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/315
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/314
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/313
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/312
- [ ] https://github.com/consensus-shipyard/fendermint/issues/193
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/310
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/309
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/308
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/307
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/227
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/280
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/278
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/277
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/270
```
