### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/ipc#266]
This is an epic to cover producing periodic snapshots of the chain state, offering them through ABCI and loading them from remote nodes. 

It is an important feature because the Calibration Net of Filecoin only offers 16 hour lookbacks on historical blocks, which cripples the IPC implementation. That's because new joiners can only get the meta-data of top-down messages from the subnet, for the actual messages they have to go to the parent chain, which after 16 hours rejects their request for data. If we had snapshots, new joiners could start syncing blocks from a less-than-16h state and only visit the parent chain for whatever is newer than that.

```[tasklist]
### Tasks
- [ ] https://github.com/consensus-shipyard/fendermint/issues/354
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/186
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/185
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/184
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/183
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/175
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/182
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/181
- [ ] https://github.com/consensus-shipyard/fendermint/issues/367
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/180
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/179
- [ ] https://github.com/consensus-shipyard/fendermint/issues/364
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/176
- [ ] https://github.com/consensus-shipyard/ipc-monorepo/issues/178
```
