### ISSUE TITLE
IPC-JS: IPC JS Provider and subnet visualizer

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#359]
```[tasklist]
### Tasks
- [ ] Write IPC provider JS functions to interact with subnets.
- [ ] Makefile rule to pull the IPC contracts ABI into the JS provider code.
- [ ] Read config for the provider.
- [ ] More to come... 
```
