### ISSUE TITLE
Road to LabWeek: Launch tasks

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#375]
List of tasks that we should have up and ready for LabWeek.

```[tasklist]
### Tasks
- [ ] Deployment of a stable "official" instance of IPC contracts in calibration that we will point devs to.
- [ ] Update all docs and code to use these contracts and calibration as the default IPC instance.
- [ ] Simple quickstart or boilerplate recipe that we will point developers as an entrypoint.
- [ ] Doc site or IPC website?
- [ ] Deployment of a public Fendermint instance hosted by the team for users looking to test IPC without running a subnet
- [ ] `Something missing? Add here!`
```
