### ISSUE TITLE
Update methods in provider and cli for new version of contracts

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#378]
The contracts have suffered a complete refactor, and there are a set of methods in the cli and provider that need to be rewritten, as well as some new operations that need to be exposed to users.

```
### Tasks
- [x] Method for validators to stake in the subnet when they have already joined.
- [x] Refactor methods to set validator metadata once they've joined (net-address and worker address)
- [x] Change join to use the new validator metadata argument.
- [x] Method for validators to be able to claim their stake.
- [ ] (optional) Command to create child subnet genesis and deploy the infrastructure
- [ ] List existing active validators
- [x] Add bootstrap command for validators in im cli
```
