### ISSUE TITLE
GMP: Sample IPC-enabled ERC-20/USDC contract

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#533]
```
Write an example contract that is IPC-enabled and supports the execution of cross-net messages. Inspiration from the Fluence case design can be found here.
```

* create a hardhat script workflow and solidity smart contracts that:
  * on parent network:
    * sets up dev environment with a gateway, subnet registry and a deployed subnet (currently the make file does this, or should do this in ./contracts)
    * creates a basic erc20 and mints some supply to the hardhat user account (MyToken.sol contract)
    * creates a basic deposit contract that uses the IPC sdk (TokenTransferAndMint contract)
    * Approve tokens to be used by basic deposit contract
    * TokenTransferAndMint is inheriting from ERC20TokenMessenger and I will want to make a small PR to allow for inheritance
    * deposit tokens into the IPC token bridge:
      * lock up tokens (currently done through here)
      * create IPC message that mints proxy token on subnet ( Currently stubbed out)
  * on subnet:
    * deploys bridge contract that
      * deploys a proxy token contract of which it is the sole owner (done)
      * receives IPC xnet message and mints subnet usdc proxy token based on the ipc message (todo)
        * overrides \\\\\\\\\\\\\\\_handleIpcCall (todo, if that is correct)
      * accepts subnet usdc proxy token deposits which triggers an xnet message to the parent network to release locked tokens to a destination address (todo)
  * on parent network:
    * receives IPC xnet message and releases usdc on the parent network

```
next steps for his USDC bridging work
```

```
### Tasks
- [x] 1. Local tests with hardhat and stubbed IPC components
- [x] 2. Unstub the sending side
- [x] 3. Make bridge contracts implement IpcHandler
- [x] 3a. Follow RecorderIpcExchange to implement virtual _handle* methods
[Further tasks have been split into separate issues]
```

```
.
```
