### ISSUE TITLE
Gossip votes about top-down finality

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/ipc#541]
Currently top-down finality proposals work by a validator proposing to the others what they think is final on the parent chain, and then hope that they see it as final as well. If they don't, they won't vote on the proposed block, which negatively affects CometBFT liveness.

Our other ace in the sleeve was to use the voting mechanism added to the IPLD Resolver to first agree on the finality off-chain, and then propose knowing that it will pass the bar. We could add a quorum certificate to the proposal, but the minimal solution is to keep the block voting as it is, and just use the IPLD Resolver to prevent introducing proposals that are bound to fail.

Votes would be cast on `(BlockHeight, BlockHash)` pairs. This needs an extension in the library to allow generic voting records; currently it's just a CID you can vote on.

Votes will be cast on different heights by different nodes; to make it easier to find common ground, we will try to find the Last Common Ancestor among the different votes; in other words a vote on a block is implicitly a vote on of its ancestors, so if Alice votes on B100 as final, and Bob votes on B105 as final, and Alice knows about blocks 101-105, just doesn't see them as deep enough yet, she can still use Bob's vote as support for B100, because she knows it's an ancestor of B105.

The goal here is to refactor the top-down proposals to be based on this voting mechanism going on in the background, and to add the necessary calls to cast votes.

Nodes should only vote on things they truly perceive as final; there shouldn't be a reason to revoke votes due to reorgs for example, nor is there a mechanism to do so.

```
### Tasks
- [ ] https://github.com/consensus-shipyard/ipc/issues/544
- [ ] https://github.com/consensus-shipyard/ipc/issues/550
- [ ] https://github.com/consensus-shipyard/ipc/issues/576
- [ ] https://github.com/consensus-shipyard/ipc/issues/586
- [ ] https://github.com/consensus-shipyard/ipc/issues/585
- [ ] https://github.com/consensus-shipyard/ipc/issues/583
- [ ] https://github.com/consensus-shipyard/ipc/issues/579
- [ ] https://github.com/consensus-shipyard/ipc/issues/578
- [ ] https://github.com/consensus-shipyard/ipc/issues/612
```
