### ISSUE TITLE
Top-down finality hardening

### ISSUE THREAD

**Issue by maciejwitowski** [consensus-shipyard/ipc#924]
- [ ] https://github.com/consensus-shipyard/ipc/issues/934
- [ ] https://github.com/consensus-shipyard/ipc/issues/863
- [ ] https://github.com/consensus-shipyard/ipc/issues/933
- [ ] https://github.com/consensus-shipyard/ipc/issues/935
- [ ] https://github.com/consensus-shipyard/ipc/issues/936
- [ ] https://github.com/consensus-shipyard/ipc/issues/937
- [ ] https://github.com/consensus-shipyard/ipc/issues/938
